version: '3.7'

services:

  guestdev:
    container_name: gestkpi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - '{pwd}:/app'
    - '/app/node_modules'
    ports:
    - '3000:3000'
    environment:
    - NODE_ENV=development